# Dracula+ colors

background #212121
foreground #f0f0ea # Dracula+ is #f8f8f2
selection_background #f8f8f2
selection_foreground #545454
cursor #FFFFFF

color0  #21222c
color1  #ff5555
color2  #50fa7b
color3  #ffcb6b
color4  #82aaff
color5  #c792ea
color6  #8be9fd
color7  #f8f8f2
color8  #545454
color9  #ff6e6e
color10 #69ff94
color11 #ffcb6b
color12 #d6acff
color13 #ff92df
color14 #a4ffff
color15 #f8f8f2

# Font

font_family DejaVu Sans Mono
font_size 18
adjust_line_height 108%

# Window

remember_window_size no
initial_window_width 10000c
initial_window_height 10000c
window_padding_width 5
macos_titlebar_color #191919
allow_remote_control yes

# Tabs

tab_bar_edge top
tab_bar_style separator
tab_separator ""
tab_title_template "  {title}  "
active_tab_foreground #f8f8f2
active_tab_background #333333
active_tab_font_style normal
inactive_tab_foreground #545454
inactive_tab_background #212121
inactive_tab_font_style normal
tab_bar_background #191919

# Keybindings

map cmd+k clear_terminal scroll active
