# :vim:ft=conf:

# If we don't list mas explicitly, brew bundle cleanup will remove it.
brew 'mas'

brew 'bat'
brew 'entr'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'jq'
brew 'lazygit'
brew 'mise'
brew 'neovim'
brew 'ripgrep'
brew 'wget'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask_args force: true
cask 'kitty'
cask 'notion'
cask 'obsidian'
cask 'raycast'
cask 'scroll-reverser'
cask 'visual-studio-code'
mas 'Xcode', id: 497799835
cask 'zed'

cask 'font-inconsolata-nerd-font'

# mason.nvim needs these to build gems:
brew 'coreutils'
brew 'libyaml'
