# ------------------------------------------------------------------------------------------
# Start with clean paths.

export PATH=/usr/bin:/bin:/usr/sbin:/sbin
export MANPATH=/usr/share/man

# ------------------------------------------------------------------------------------------
# Set up homebrew.
#
# https://brew.sh

if [[ -x /opt/homebrew/bin/brew ]] {
  export HOMEBREW_NO_ENV_HINTS=true

  eval "$(/opt/homebrew/bin/brew shellenv)"

  fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)
  fpath=($HOMEBREW_PREFIX/share/zsh-completions $fpath)
}

# ------------------------------------------------------------------------------------------
# Set up mise.
#
# https://mise.jdx.dev

if [[ -x $HOMEBREW_PREFIX/bin/mise ]] {
  eval "$(mise activate zsh --shims)"
}

# Make Neovim my default editor.
if [[ -x $HOMEBREW_PREFIX/bin/nvim ]] {
  export EDITOR=$HOMEBREW_PREFIX/bin/nvim
}

# ------------------------------------------------------------------------------------------
# Decide whether this is a home or work machine, based on the hostname.

case $(hostname -s) {
  Knuth)
    export DOTFILES_ENV=home;;
  *)
    export DOTFILES_ENV=work;;
}

# ------------------------------------------------------------------------------------------
# Set various helpful things for work.

if [[ $DOTFILES_ENV == 'work' ]] {
  export UP_HOME_PATH=$HOME/src/up

  export ANDROID_HOME=$HOME/Library/Android/sdk

  export PATH=$ANDROID_HOME/emulator:$PATH
  export PATH=$ANDROID_HOME/tools:$PATH
  export PATH=$ANDROID_HOME/tools/bin:$PATH
  export PATH=$ANDROID_HOME/platform-tools:$PATH
  export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
}

# ------------------------------------------------------------------------------------------
# Prevent the MacOS /etc/zprofile running its path helper and adding all sorts
# of unnecessary nonsense to my path.

unsetopt global_rcs
