# echo ".zshenv $$"

# ------------------------------------------------------------------------------------------
# Start with clean paths.

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin:$HOME/.rd/bin
export MANPATH=/usr/share/man

# ------------------------------------------------------------------------------------------
# Decide whether this is a home or work machine, based on the hostname.

case $(scutil --get LocalHostName) {
  fer-*)
    export DOTFILES_ENV=work;;
  *)
    export DOTFILES_ENV=home;;
}

# ------------------------------------------------------------------------------------------
# Set up homebrew.
#
# https://brew.sh

if [[ -x /opt/homebrew/bin/brew ]] {
  export HOMEBREW_NO_ENV_HINTS=true

  eval "$(/opt/homebrew/bin/brew shellenv)"

  fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)
  fpath=($HOMEBREW_PREFIX/share/zsh-completions $fpath)
}

# ------------------------------------------------------------------------------------------
# Set up mise.
#
# https://mise.jdx.dev

if [[ $DOTFILES_ENV == 'work' ]] {
  export MISE_LOCATION=$HOME/.local/bin/mise
} else {
  export MISE_LOCATION=$HOMEBREW_PREFIX/bin/mise
}

if [[ -x $MISE_LOCATION ]] {
  eval "$(mise activate zsh --shims)"
}

# ------------------------------------------------------------------------------------------
# Make Neovim my default editor.

if [[ -x $HOMEBREW_PREFIX/bin/nvim ]] {
  export EDITOR=$HOMEBREW_PREFIX/bin/nvim
}

# ------------------------------------------------------------------------------------------
# Set various helpful things for work.

if [[ -a $HOME/.zshenv-work ]] {
  source $HOME/.zshenv-work
}

# ------------------------------------------------------------------------------------------
# Prevent the MacOS /etc/zprofile running its path helper and adding all sorts
# of unnecessary nonsense to my path.

unsetopt global_rcs
