# Start with a clean path.
export PATH=/usr/bin:/bin:/usr/sbin:/sbin

if [[ -f /opt/homebrew/bin/brew ]] {
  export HOMEBREW_NO_ENV_HINTS=true

  eval "$(/opt/homebrew/bin/brew shellenv)"

  fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)
  fpath=($HOMEBREW_PREFIX/share/zsh-completions $fpath)
}

if [[ -f $HOMEBREW_PREFIX/bin/mise ]] {
  eval "$(mise activate zsh --shims)"
}

if [[ -f $HOMEBREW_PREFIX/bin/nvim ]] {
  export EDITOR=$HOMEBREW_PREFIX/bin/nvim
}

case $(hostname -s) {
  Knuth)
    export DOTFILES_ENV=home;;
  *)
    export DOTFILES_ENV=work;;
}

# Prevent the MacOS /etc/zprofile running its path helper and adding all sorts
# of unnecessary nonsense to my path.
alias /usr/libexec/path_helper=true
