#!/usr/bin/env ruby

exit 0 unless File.file?(File.join(Dir.pwd, 'Rakefile'))
exit 0 unless /^rake(?:\s+([-\w]+))?\s*$/ =~ ENV["COMP_LINE"]

task_prefix = $1

# Customize this line to where you want to put the rake task caches
task_file = File.join(Dir.pwd, '._rake_tasks')

if File.file?(task_file)
  tasks = IO.read(task_file).split
else
  tasks = `rake --tasks`.split("\n")[1..-1].collect {|line| line.split[1]}
  begin File.open(task_file, 'w') {|f| f.write tasks.join(' ') }
  rescue Exception
  end
end

tasks = tasks.select {|t| /^#{Regexp.escape task_prefix}/ =~ t} if task_prefix

puts tasks
exit 0
